version: '3'

services:
  db:
    image: mysql:8.0.36
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3303:3306" ### changed 
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/wp_db_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER_FILE: /run/secrets/wp_db_username
      MYSQL_PASSWORD_FILE: /run/secrets/wp_db_password
    secrets:
      - wp_db_password
      - wp_db_username
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u $$MYSQL_USER -p$$MYSQL_PASSWORD ping -h localhost || exit 1"]
      start_period: 10s
      interval: 2s
      timeout: 5s
      retries: 20
      
  wordpress:
    image: my_wordpress:latest
    volumes:
      - wordpress:/var/www/html:rw
    ports:
      - "8085:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER_FILE: /run/secrets/wp_db_username
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wp_db_password
      WORDPRESS_DB_NAME: wordpress
    secrets:
      - wp_db_password
      - wp_db_username

  adminer:
    depends_on: 
      - db
    image: adminer:latest
    restart: always
    ports: 
      - 8889:8080

volumes:
  wordpress:
  db-data:

secrets:
  wp_db_password:
    external: true
  wp_db_username:
    external: true